### ISSUE TITLE
Command to start/stop all services?

### ISSUE THREAD

**Issue by dimaspivak** [jimbobhickville/python-ambariclient#26]
This project is beautiful and really makes working with Ambari incredibly straightforward. The only thing I haven't been able to find out from my examination of the docs and the code is how to invoke the "Start all services" endpoint that Ambari has for a given cluster. The [corresponding code](https://github.com/apache/ambari/blob/branch-2.5/ambari-client/python-client/src/main/python/ambari_client/model/cluster.py#L160-L182) looks straightforward enough, so it is just a question of the functionality not being present or am I overlooking something obvious?

**Comment by jimbobhickville** [comment]
I honestly don't recall why it is that way. It's possible that ambari-server stopped working properly with that code. The official Python client was basically abandoned which is why I wrote this one. Not sure if that situation has changed, as I've changed jobs and no longer work with Ambari.

There is `client.clusters(name).services.restart()` which should start any that aren't currently up in addition to restarting the ones that are up.  

https://github.com/jimbobhickville/python-ambariclient/blob/master/ambariclient/models.py#L683

Seems like you could just copy that, change `RESTART` to `START` and it might do what you need.

**Comment by dimaspivak** [comment]
:) Cool, glad it wasn’t intentionally left out. Let me get a PR to add the functionality here; it works perfectly in my fork.

**Comment by jimbobhickville** [comment]
PR merged
